#
# Copyright (c) 2015, Oracle and/or its affiliates. All rights reserved.
#

include $(CTI_ROOT)/Makefiles/Makefile.defs

CTI_SUBDIRS = python

all clean clobber install : $(CTI_SUBDIRS)

include $(CTI_ROOT)/Makefiles/Makefile.targ
